### ISSUE TITLE
Advice for downloading

### ISSUE THREAD

**Issue by davodogster** [ghiggi/himawari_api#1]
Hello, thanks for the package.

I need to automatically download recent files/images from Himawari-9 NZ. Then I want to produce True Colour Reproduction.
Could you please provide some advice how I can use your package for this? 

I have these modules installed:
import himawari_api
from satpy import Scene, MultiScene
from dask.diagnostics import ProgressBar

Best regards,

Sam

**Comment by ghiggi** [comment]
This tutorial should provide you the answers @davodogster : 

https://github.com/ghiggi/himawari_api/blob/main/tutorials/03_read_ahi_rad_nrt_data_with_satpy.py 

Maybe have a look also to the others tutorials ;) 

Let me know if something doesn't work ;)
